name: ml-assignment-1
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - python=3.7
  - scikit-image
  - scikit-learn
  - scipy
  - wheel
  - pip:
    - opencv-python
    - pyglet